# Financial Performance Dashboard

## 01 - Data Understanding

**Project:** Global Electronics Retailer Sales Analysis

**Objective:**
Understand the dataset, identify relationships between tables,
inspect data quality, and prepare for cleaning.

## Import Required Libraries

In this section we import the Python libraries required for data analysis.

In [23]:
import pandas as pd
import numpy as np

print("Pandas:", pd.__version__)
print("NumPy:", np.__version__)
print("Environment Ready!")

Pandas: 2.3.1
NumPy: 2.1.3
Environment Ready!

## Load the Datasets

Load all business datasets into Pandas DataFrames for further analysis.

In [24]:
customers = pd.read_csv("../data/Customers.csv", encoding="cp1252")
products = pd.read_csv("../data/Products.csv", encoding="cp1252")
sales = pd.read_csv("../data/Sales.csv", encoding="cp1252")
stores = pd.read_csv("../data/Stores.csv", encoding="cp1252")
exchange_rates = pd.read_csv("../data/Exchange_Rates.csv", encoding="cp1252")

## Verify Dataset Loading

Check whether all datasets have been loaded successfully and inspect their dimensions.

In [25]:
datasets = {
    "Customers": customers,
    "Products": products,
    "Sales": sales,
    "Stores": stores,
    "Exchange Rates": exchange_rates
}

for name, df in datasets.items():
    print(f"{name:<20} : {df.shape[0]:>7} rows × {df.shape[1]} columns")

Customers            :   15266 rows × 10 columns
Products             :    2517 rows × 10 columns
Sales                :   62884 rows × 9 columns
Stores               :      67 rows × 5 columns
Exchange Rates       :   11215 rows × 3 columns

## Display Column Names

Review the available columns in each dataset to understand the data structure.

In [26]:
for name, df in datasets.items():
    print("=" * 60)
    print(name)
    print("=" * 60)
    print(df.columns.tolist())
    print()

============================================================
Customers
============================================================
['CustomerKey', 'Gender', 'Name', 'City', 'State Code', 'State', 'Zip Code', 'Country', 'Continent', 'Birthday']

============================================================
Products
============================================================
['ProductKey', 'Product Name', 'Brand', 'Color', 'Unit Cost USD', 'Unit Price USD', 'SubcategoryKey', 'Subcategory', 'CategoryKey', 'Category']

============================================================
Sales
============================================================
['Order Number', 'Line Item', 'Order Date', 'Delivery Date', 'CustomerKey', 'StoreKey', 'ProductKey', 'Quantity', 'Currency Code']

============================================================
Stores
============================================================
['StoreKey', 'Country', 'State', 'Square Meters', 'Open Date']

============================================================
Exchange Rates
============================================================
['Date', 'Currency', 'Exchange']

## Preview the Datasets

Display the first five records of each dataset to understand the structure and available information.

In [27]:
for name, df in datasets.items():
    print("=" * 80)
    print(name)
    print("=" * 80)
    display(df.head())

================================================================================
Customers
================================================================================

,CustomerKey,Gender,Name,City,State Code,State,Zip Code,Country,Continent,Birthday
0,301,Female,Lilly Harding,WANDEARAH EAST,SA,South Australia,5523,Australia,Australia,7/3/1939
1,325,Female,Madison Hull,MOUNT BUDD,WA,Western Australia,6522,Australia,Australia,9/27/1979
2,554,Female,Claire Ferres,WINJALLOK,VIC,Victoria,3380,Australia,Australia,5/26/1947
3,786,Male,Jai Poltpalingada,MIDDLE RIVER,SA,South Australia,5223,Australia,Australia,9/17/1957
4,1042,Male,Aidan Pankhurst,TAWONGA SOUTH,VIC,Victoria,3698,Australia,Australia,11/19/1965

================================================================================
Products
================================================================================

,ProductKey,Product Name,Brand,Color,Unit Cost USD,Unit Price USD,SubcategoryKey,Subcategory,CategoryKey,Category
0,1,Contoso 512MB MP3 Player E51 Silver,Contoso,Silver,$6.62,$12.99,101,MP4&MP3,1,Audio
1,2,Contoso 512MB MP3 Player E51 Blue,Contoso,Blue,$6.62,$12.99,101,MP4&MP3,1,Audio
2,3,Contoso 1G MP3 Player E100 White,Contoso,White,$7.40,$14.52,101,MP4&MP3,1,Audio
3,4,Contoso 2G MP3 Player E200 Silver,Contoso,Silver,$11.00,$21.57,101,MP4&MP3,1,Audio
4,5,Contoso 2G MP3 Player E200 Red,Contoso,Red,$11.00,$21.57,101,MP4&MP3,1,Audio

================================================================================
Sales
================================================================================

,Order Number,Line Item,Order Date,Delivery Date,CustomerKey,StoreKey,ProductKey,Quantity,Currency Code
0,366000,1,1/1/2016,NaN,265598,10,1304,1,CAD
1,366001,1,1/1/2016,1/13/2016,1269051,0,1048,2,USD
2,366001,2,1/1/2016,1/13/2016,1269051,0,2007,1,USD
3,366002,1,1/1/2016,1/12/2016,266019,0,1106,7,CAD
4,366002,2,1/1/2016,1/12/2016,266019,0,373,1,CAD

================================================================================
Stores
================================================================================

   StoreKey    Country                         State  Square Meters  Open Date
0         1  Australia  Australian Capital Territory          595.0   1/1/2008
1         2  Australia            Northern Territory          665.0  1/12/2008
2         3  Australia               South Australia         2000.0   1/7/2012
3         4  Australia                      Tasmania         2000.0   1/1/2010
4         5  Australia                      Victoria         2000.0  12/9/2015

================================================================================
Exchange Rates
================================================================================

       Date Currency  Exchange
0  1/1/2015      USD    1.0000
1  1/1/2015      CAD    1.1583
2  1/1/2015      AUD    1.2214
3  1/1/2015      EUR    0.8237
4  1/1/2015      GBP    0.6415

## Dataset Information

Inspect the data types, non-null values, and memory usage of each dataset.

In [28]:
for name, df in datasets.items():
    print("=" * 80)
    print(name)
    print("=" * 80)
    df.info()
    print("\n")

================================================================================
Customers
================================================================================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15266 entries, 0 to 15265
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   CustomerKey  15266 non-null  int64
 1   Gender       15266 non-null  object
 2   Name         15266 non-null  object
 3   City         15266 non-null  object
 4   State Code   15256 non-null  object
 5   State        15266 non-null  object
 6   Zip Code     15266 non-null  object
 7   Country      15266 non-null  object
 8   Continent    15266 non-null  object
 9   Birthday     15266 non-null  object
dtypes: int64(1), object(9)
memory usage: 1.2+ MB


================================================================================
Products
================================================================================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2517 entries, 0 to 2516
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   ProductKey      2517 non-null   int64
 1   Product Name    2517 non-null   object
 2   Brand           2517 non-null   object
 3   Color           2517 non-null   object
 4   Unit Cost USD   2517 non-null   object
 5   Unit Price USD  2517 non-null   object
 6   SubcategoryKey  2517 non-null   int64
 7   Subcategory     2517 non-null   object
 8   CategoryKey     2517 non-null   int64
 9   Category        2517 non-null   object
dtypes: int64(3), object(7)
memory usage: 196.8+ KB


================================================================================
Sales
================================================================================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 62884 entries, 0 to 62883
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Order Number   62884 non-null  int64
 1   Line Item      62884 non-null  int64
 2   Order Date     62884 non-null  object
 3   Delivery Date  13165 non-null  object
 4   CustomerKey    62884 non-null  int64
 5   StoreKey       62884 non-null  int64
 6   ProductKey     62884 non-null  int64
 7   Quantity       62884 non-null  int64
 8   Currency Code  62884 non-null  object
dtypes: int64(6), object(3)
memory usage: 4.3+ MB


================================================================================
Stores
================================================================================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 67 entries, 0 to 66
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   StoreKey       67 non-null     int64
 1   Country        67 non-null     object
 2   State          67 non-null     object
 3   Square Meters  66 non-null     float64
 4   Open Date      67 non-null     object
dtypes: float64(1), int64(1), object(3)
memory usage: 2.7+ KB


================================================================================
Exchange Rates
================================================================================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11215 entries, 0 to 11214
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Date      11215 non-null  object
 1   Currency  11215 non-null  object
 2   Exchange  11215 non-null  float64
dtypes: float64(1), object(2)
memory usage: 263.0+ KB

## Missing Values Analysis

Identify missing values in each dataset before data cleaning.

In [29]:
for name, df in datasets.items():
    print("=" * 80)
    print(name)
    print("=" * 80)
    print(df.isnull().sum())
    print("\n")

================================================================================
Customers
================================================================================
CustomerKey     0
Gender          0
Name            0
City            0
State Code     10
State           0
Zip Code        0
Country         0
Continent       0
Birthday        0
dtype: int64


================================================================================
Products
================================================================================
ProductKey        0
Product Name      0
Brand             0
Color             0
Unit Cost USD     0
Unit Price USD    0
SubcategoryKey    0
Subcategory       0
CategoryKey       0
Category          0
dtype: int64


================================================================================
Sales
================================================================================
Order Number         0
Line Item            0
Order Date           0
Delivery Date    49719
CustomerKey          0
StoreKey             0
ProductKey           0
Quantity             0
Currency Code        0
dtype: int64


================================================================================
Stores
================================================================================
StoreKey         0
Country          0
State            0
Square Meters    1
Open Date        0
dtype: int64


================================================================================
Exchange Rates
================================================================================
Date        0
Currency    0
Exchange    0
dtype: int64

## Descriptive Statistics

Generate summary statistics for all numerical columns.

In [30]:
for name, df in datasets.items():
    print("=" * 80)
    print(name)
    print("=" * 80)
    display(df.describe())

================================================================================
Customers
================================================================================

        CustomerKey
count  1.526600e+04
mean   1.060508e+06
std    6.127097e+05
min    3.010000e+02
25%    5.140335e+05
50%    1.079244e+06
75%    1.593980e+06
max    2.099937e+06

================================================================================
Products
================================================================================

        ProductKey  SubcategoryKey  CategoryKey
count  2517.000000     2517.000000  2517.000000
mean   1259.000000      491.810091     4.878824
std     726.739637      229.887134     2.299170
min       1.000000      101.000000     1.000000
25%     630.000000      305.000000     3.000000
50%    1259.000000      406.000000     4.000000
75%    1888.000000      801.000000     8.000000
max    2517.000000      808.000000     8.000000

================================================================================
Sales
================================================================================

,Order Number,Line Item,CustomerKey,StoreKey,ProductKey,Quantity
count,6.288400e+04,62884.000000,6.288400e+04,62884.000000,62884.000000,62884.000000
mean,1.430905e+06,2.164207,1.180797e+06,31.802144,1125.859344,3.144790
std,4.532963e+05,1.365170,5.859634e+05,22.978188,709.244010,2.256371
min,3.660000e+05,1.000000,3.010000e+02,0.000000,1.000000,1.000000
25%,1.121017e+06,1.000000,6.808580e+05,8.000000,437.000000,1.000000
50%,1.498016e+06,2.000000,1.261200e+06,37.000000,1358.000000,2.000000
75%,1.788010e+06,3.000000,1.686496e+06,53.000000,1650.000000,4.000000
max,2.243032e+06,7.000000,2.099937e+06,66.000000,2517.000000,10.000000

================================================================================
Stores
================================================================================

        StoreKey  Square Meters
count  67.000000      66.000000
mean   33.000000    1402.196970
std    19.485037     576.404058
min     0.000000     245.000000
25%    16.500000    1108.750000
50%    33.000000    1347.500000
75%    49.500000    2000.000000
max    66.000000    2105.000000

================================================================================
Exchange Rates
================================================================================

           Exchange
count  11215.000000
mean       1.061682
std        0.245519
min        0.628500
25%        0.857800
50%        1.000000
75%        1.311900
max        1.725300

# Business Understanding

This project analyzes the operations of a global electronics retailer.

The dataset consists of five core business tables:

- Customers
- Products
- Sales
- Stores
- Exchange Rates

The objective is to understand how customers purchase products across different stores and countries while evaluating financial performance, profitability, and sales trends.

## Identify Primary Keys and Foreign Keys

Understanding the relationships between tables is essential before building SQL queries and Power BI dashboards.

In [31]:
for name, df in datasets.items():
    print("=" * 80)
    print(name)
    print("=" * 80)
    print(df.columns.tolist())
    print()

================================================================================
Customers
================================================================================
['CustomerKey', 'Gender', 'Name', 'City', 'State Code', 'State', 'Zip Code', 'Country', 'Continent', 'Birthday']

================================================================================
Products
================================================================================
['ProductKey', 'Product Name', 'Brand', 'Color', 'Unit Cost USD', 'Unit Price USD', 'SubcategoryKey', 'Subcategory', 'CategoryKey', 'Category']

================================================================================
Sales
================================================================================
['Order Number', 'Line Item', 'Order Date', 'Delivery Date', 'CustomerKey', 'StoreKey', 'ProductKey', 'Quantity', 'Currency Code']

================================================================================
Stores
================================================================================
['StoreKey', 'Country', 'State', 'Square Meters', 'Open Date']

================================================================================
Exchange Rates
================================================================================
['Date', 'Currency', 'Exchange']

In [32]:
for name, df in datasets.items():
    print("=" * 80)
    print(name)
    print("=" * 80)
    print(df.columns.tolist())
    print()

================================================================================
Customers
================================================================================
['CustomerKey', 'Gender', 'Name', 'City', 'State Code', 'State', 'Zip Code', 'Country', 'Continent', 'Birthday']

================================================================================
Products
================================================================================
['ProductKey', 'Product Name', 'Brand', 'Color', 'Unit Cost USD', 'Unit Price USD', 'SubcategoryKey', 'Subcategory', 'CategoryKey', 'Category']

================================================================================
Sales
================================================================================
['Order Number', 'Line Item', 'Order Date', 'Delivery Date', 'CustomerKey', 'StoreKey', 'ProductKey', 'Quantity', 'Currency Code']

================================================================================
Stores
================================================================================
['StoreKey', 'Country', 'State', 'Square Meters', 'Open Date']

================================================================================
Exchange Rates
================================================================================
['Date', 'Currency', 'Exchange']

# Business Data Model

The Global Electronics Retailer dataset follows a relational database model.

## Tables

### Customers
Stores customer demographic and location information.

**Primary Key**
- CustomerKey

---

### Products
Contains information about electronic products.

**Primary Key**
- ProductKey

---

### Stores
Contains store information such as country, state, square meters, and opening date.

**Primary Key**
- StoreKey

---

### Sales
Stores every sales transaction.

**Primary Key**
- Order Number (or OrderNumber if available)

**Foreign Keys**
- CustomerKey
- ProductKey
- StoreKey
- Currency Code

---

### Exchange Rates
Contains daily exchange rates for different currencies.

**Primary Key**
- Date + Currency

Used to convert sales into a common reporting currency.

# Relationship Between Tables

Customers
        │
        │ CustomerKey
        ▼
      Sales
   ▲     │      ▲
   │     │      │
StoreKey │ ProductKey
   │     │
Stores   Products
        │
        ▼
 Exchange Rates

# Business Workflow

The business process can be summarized as follows:

1. A customer visits a store.
2. The customer purchases one or more products.
3. Each purchase is recorded in the Sales table.
4. Every sale references:
   - Customer
   - Product
   - Store
   - Currency
5. Exchange rates are used to standardize financial reporting across countries.

# Summary

## Key Findings

- Successfully loaded all datasets.
- Verified dataset dimensions.
- Reviewed column names and data types.
- Identified missing values.
- Generated descriptive statistics.
- Understood the business model.
- Identified primary and foreign keys.
- Prepared the dataset for data cleaning.

## Next Step

Notebook 02 — Data Cleaning

Tasks:
- Handle missing values
- Remove duplicates
- Convert data types
- Standardize column names
- Validate data quality